---
namespace: nbeernink
name: cvad
description: Collection of modules for interacting with the Citrix Virtual Apps and Desktop API
version: 0.0.2
readme: README.md

authors:
 - Niek Beernink


repository: https://github.com/nbeernink/cvad-ansible-modules

license:
 - GPL-3.0-or-later

tags:
 - citrix
 - cvad

dependencies: {}
